// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// HookFunc is an autogenerated mock type for the HookFunc type
type HookFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: db
func (_m *HookFunc) Execute(db *gorm.DB) {
	_m.Called(db)
}

type mockConstructorTestingTNewHookFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewHookFunc creates a new instance of HookFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHookFunc(t mockConstructorTestingTNewHookFunc) *HookFunc {
	mock := &HookFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
