#!/bin/sh

# This script is a commit-msg hook to validate commit message format for Conventional Commits 1.0.0

commit_regex='^(build|chore|ci|docs|feat|fix|perf|refactor|style|test|BREAKING CHANGE)(\(.+\))?!?: .+'
error_msg="Commit message does not follow the Conventional Commits 1.0.0 format: https://www.conventionalcommits.org"

# If it's not a merge commit
if ! grep -qE "^Merge" "$1"; then
    # Check if the first line of commit message matches the regex
    if ! head -n1 "$1" | grep -qE "$commit_regex"; then
        echo "$error_msg" >&2
        exit 1
    fi
fi
