// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	message "github.com/christian-gama/nutrai-api/internal/core/domain/message"
	mock "github.com/stretchr/testify/mock"
)

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

// Handle provides a mock function with given fields: handler
func (_m *Consumer) Handle(handler message.MessageHandler) {
	_m.Called(handler)
}

type mockConstructorTestingTNewConsumer interface {
	mock.TestingT
	Cleanup(func())
}

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConsumer(t mockConstructorTestingTNewConsumer) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
