global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nutrai-api"
    scrape_interval: 5s
    metrics_path: /internal/metrics
    scheme: http
    static_configs:
      - targets: ["api:8080"]
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/prometheus-credentials

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
