apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    isDefault: true

  - name: PostgresSQL
    type: postgres
    url: psql:$DB_PORT
    database: "$DB_NAME"
    user: "$DB_USER"
    editable: true
    secureJsonData:
      password: "$DB_PASSWORD"
    jsonData:
      sslmode: "$DB_SSL_MODE"
      maxOpenConns: 100
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false
