// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	value "github.com/christian-gama/nutrai-api/internal/core/domain/value"
)

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *Generator) Generate() value.UUID {
	ret := _m.Called()

	var r0 value.UUID
	if rf, ok := ret.Get(0).(func() value.UUID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(value.UUID)
	}

	return r0
}

type mockConstructorTestingTNewGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewGenerator creates a new instance of Generator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGenerator(t mockConstructorTestingTNewGenerator) *Generator {
	mock := &Generator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
