// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/christian-gama/nutrai-api/internal/gpt/app/service"
	mock "github.com/stretchr/testify/mock"
)

// ChatCompletion is an autogenerated mock type for the ChatCompletion type
type ChatCompletion struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, input
func (_m *ChatCompletion) Execute(ctx context.Context, input *service.ChatCompletionInput) (*service.ChatCompletionOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 *service.ChatCompletionOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.ChatCompletionInput) (*service.ChatCompletionOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *service.ChatCompletionInput) *service.ChatCompletionOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.ChatCompletionOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *service.ChatCompletionInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewChatCompletion interface {
	mock.TestingT
	Cleanup(func())
}

// NewChatCompletion creates a new instance of ChatCompletion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChatCompletion(t mockConstructorTestingTNewChatCompletion) *ChatCompletion {
	mock := &ChatCompletion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
