// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SaveExceptionHandler is an autogenerated mock type for the SaveExceptionHandler type
type SaveExceptionHandler struct {
	mock.Mock
}

// ConsumerHandler provides a mock function with given fields: body
func (_m *SaveExceptionHandler) ConsumerHandler(body []byte) error {
	ret := _m.Called(body)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Handle provides a mock function with given fields:
func (_m *SaveExceptionHandler) Handle() {
	_m.Called()
}

type mockConstructorTestingTNewSaveExceptionHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewSaveExceptionHandler creates a new instance of SaveExceptionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSaveExceptionHandler(t mockConstructorTestingTNewSaveExceptionHandler) *SaveExceptionHandler {
	mock := &SaveExceptionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
