// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	exception "github.com/christian-gama/nutrai-api/internal/exception/domain/model/exception"
	mock "github.com/stretchr/testify/mock"
)

// SaveExceptionHandler is an autogenerated mock type for the SaveExceptionHandler type
type SaveExceptionHandler struct {
	mock.Mock
}

// ConsumerHandler provides a mock function with given fields: e
func (_m *SaveExceptionHandler) ConsumerHandler(e exception.Exception) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(exception.Exception) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Handle provides a mock function with given fields:
func (_m *SaveExceptionHandler) Handle() {
	_m.Called()
}

type mockConstructorTestingTNewSaveExceptionHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewSaveExceptionHandler creates a new instance of SaveExceptionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSaveExceptionHandler(t mockConstructorTestingTNewSaveExceptionHandler) *SaveExceptionHandler {
	mock := &SaveExceptionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
