// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidModel is an autogenerated mock type for the ValidModel type
type ValidModel struct {
	mock.Mock
}

// Validate provides a mock function with given fields:
func (_m *ValidModel) Validate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewValidModel interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidModel creates a new instance of ValidModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidModel(t mockConstructorTestingTNewValidModel) *ValidModel {
	mock := &ValidModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
