// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	jwt "github.com/christian-gama/nutrai-api/internal/auth/domain/jwt"
	mock "github.com/stretchr/testify/mock"

	value "github.com/christian-gama/nutrai-api/internal/auth/domain/value/jwt"
)

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: data, persist
func (_m *Generator) Generate(data *jwt.Subject, persist bool) (value.Token, error) {
	ret := _m.Called(data, persist)

	var r0 value.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(*jwt.Subject, bool) (value.Token, error)); ok {
		return rf(data, persist)
	}
	if rf, ok := ret.Get(0).(func(*jwt.Subject, bool) value.Token); ok {
		r0 = rf(data, persist)
	} else {
		r0 = ret.Get(0).(value.Token)
	}

	if rf, ok := ret.Get(1).(func(*jwt.Subject, bool) error); ok {
		r1 = rf(data, persist)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewGenerator creates a new instance of Generator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGenerator(t mockConstructorTestingTNewGenerator) *Generator {
	mock := &Generator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
