// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	manager "github.com/christian-gama/nutrai-api/internal/shared/infra/manager"
	mock "github.com/stretchr/testify/mock"
)

// Update is an autogenerated mock type for the Update type
type Update[Model interface{}] struct {
	mock.Mock
}

// Update provides a mock function with given fields: ctx, input
func (_m *Update[Model]) Update(ctx context.Context, input manager.UpdateInput[Model]) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, manager.UpdateInput[Model]) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUpdate interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdate creates a new instance of Update. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdate[Model interface{}](t mockConstructorTestingTNewUpdate) *Update[Model] {
	mock := &Update[Model]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
