name: Run tests
on:
  push:
    branches:
      - dependabot/**
  pull_request:
    branches:
      - dependabot/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: ./scripts/manage_env.sh

      - name: Install dependencies
        run: make tidy

      - name: Cache test dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-test-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-test
      - name: Test
        run: make test-ci
